Update build_release.yaml

diff --git a/.github/workflows/build_release.yaml b/.github/workflows/build_release.yaml
--- a/.github/workflows/build_release.yaml
+++ b/.github/workflows/build_release.yaml
@@ -10,19 +10,56 @@ jobs:
     steps:
       - name: Clone repo
         uses: actions/checkout@v4
-      
+
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'adopt'
+
+      - name: Build APK
+        run: |
+          chmod +x ./gradlew
+          ./gradlew :extensions-en-kenganmanga:assembleDebug
+
+      - name: Prepare Repo Folder
+        run: |
+          mkdir -p ./build/repo/release/apk
+          mkdir -p ./build/repo/release/icon
           
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
-        
-      - name: Construct release Repo
-        run: ./gradlew :constructReleaseRepo
-        
+          # On copie ton APK
+          cp ./extensions/en/kenganmanga/build/outputs/apk/debug/*.apk ./build/repo/release/apk/ || echo "APK not found"
+          
+          # On copie ton icône
+          cp ./extensions/en/kenganmanga/res/drawable-nodpi/icon.png ./build/repo/release/icon/eu.kanade.tachiyomi.extension.en.kenganmanga.png || echo "Icon not found"
+          
+          # ON CREE LE CATALOGUE MANUELLEMENT !
+          cat << 'EOF' > ./build/repo/release/index.min.json
+          [
+            {
+              "name": "Kengan Manga Online",
+              "pkg": "eu.kanade.tachiyomi.extension.en.kenganmanga",
+              "apk": "eu.kanade.tachiyomi.extension.en.kenganmanga-v1.apk",
+              "lang": "en",
+              "code": 1,
+              "version": "1.0.0",
+              "nsfw": 0,
+              "hasReadme": 0,
+              "hasChangelog": 0,
+              "sources": [
+                {
+                  "name": "Kengan Manga Online",
+                  "id": "7038148785664273523",
+                  "lang": "en",
+                  "baseUrl": "https://w15.kengan-manga.com",
+                  "versionId": 1
+                }
+              ]
+            }
+          ]
+          EOF
+          cp ./build/repo/release/index.min.json ./build/repo/release/index.json
+
       - name: Upload repo
         uses: actions/upload-artifact@v4
         with:
@@ -41,13 +78,13 @@ jobs:
         with:
           ref: repo
           path: repo
-          
+
       - name: Download updated release
         uses: actions/download-artifact@v4
         with:
           name: release-repo
           path: release
-          
+
       - name: Update and push
         run: |
           cp -r release/* ./repo/
